version: '3.8'

services:
  db:
    image: ${DB_IMAGE}
    container_name: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_INTERNAL_PORT}
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  app:
    image: ${APP_IMAGE}
    container_name: ${APP_NAME}
    depends_on:
      - db
    volumes:
      - ${APP_VOLUME}:/var/www/html
      - ./INI/limits.ini:/usr/local/etc/php/conf.d/limits.ini
      - ./INI/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./INI/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped

  phpmyadmin:
    image: ${PMA_IMAGE}
    container_name: ${PMA_NAME}
    depends_on:
      - db
    volumes:
      - ./INI/limits.ini:/usr/local/etc/php/conf.d/limits.ini
      - ./INI/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./INI/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
    ports:
      - ${PMA_PORT}:80
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
