version: '3.8'

services:
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  app:
    image: php:${PHP_VERSION}
    container_name: ${APP_NAME}
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html
      - ./limits.ini:/usr/local/etc/php/conf.d/limits.ini
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ${PMA_NAME}
    depends_on:
      - db
    volumes:
      - ./limits.ini:/usr/local/etc/php/conf.d/limits.ini
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
    ports:
      - ${PMA_PORT}:80
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
